### PR TITLE
Add datetime to window title

### LINKED ISSUE #194: Make the window name default include the time
Having nameable windows to distinguish them is great, but quite manual.

I think adding the datetime to the window title might just be good as a default, so you know which order you opened them in.

### PR DESCRIPTION
**Pull request by IanButterworth**
Implements #194 but instead adds it to the end of the window name, even if  a custom one is provided.

I think knowing the order that windows were opened in may always be of value
Screen Shot 2022-01-22 at 5 05 05 PM

Closes #194

### CODE REVIEW

**Comment by timholy** [comment]
I can go with this. I worry a bit about the cognitive load of comparing times, especially if the user has gone to the trouble to give each window a unique name anyway (now we're adding a distractor with no new information).

**Comment by IanButterworth** [comment]
That's a good point. How about it's only shown for `@profview` given there the API isn't currently exposed for setting the window name? I think that might make more sense than appending it to a `ProfileView.view()` anyway because I think the time is informative wrt. the data collected, not when the window opened.

I'll give this another go

**Comment by IanButterworth** [comment]
Updated. Also, I don't feel strongly about this. Just an idea. I'd be happy to leave it out

**Comment by timholy** [comment]
I like it. Let's do it.

**Pull request merged**
