### PR TITLE
Switch to Gtk

### PR DESCRIPTION
**Pull request by timholy**
Precompilation wahoo!

### CODE REVIEW

**Comment by tkelman** [comment]
Why are the constants and imports in Main here and not module-local inside ProfileView?

**Comment by timholy** [comment]
Sorry, can you clarify? Are you talking about [these lines](https://github.com/timholy/ProfileView.jl/blob/eb400d66f8de08bf4979812f1f92fe88e470b5f6/src/ProfileView.jl#L8-L9)?

**Comment by tkelman** [comment]
no, these https://github.com/timholy/ProfileView.jl/blob/eb400d66f8de08bf4979812f1f92fe88e470b5f6/src/ProfileView.jl#L46-L57

**Comment by tkelman** [comment]
Ah okay looks like the import does end up module-local, but due to the modification of LOAD_PATH, the sub-modules get treated as if they are independent packages, they get their own ji files which is a little odd.

**Comment by timholy** [comment]
It's basically a hand-implemented conditional module without the scary method-table surgery of Requires. Since we don't have good support for those yet, it's going to be a little odd...

**Pull request merged**
