### PR TITLE
Add appveyor.yml

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by tkelman** [comment]
So Gtk.jl has issues on win32? Worth tracking down and fixing wherever the cause is, but for now could make 32 bit an allowed failure?

**Comment by timholy** [comment]
My attempt at getting the file format right clearly failed. I'm going to go ahead and tag a new release without this, but if anyone has any ideas...

**Comment by tkelman** [comment]
platform is just an msvc thing, you'd have to use the env vars for the allowed failures i think

**Comment by timholy** [comment]
That didn't work either. Any specific format suggestions?

**Comment by timholy** [comment]
Reminder to self: I turned off AppVeyor until this gets resolved; don't forget to turn back on again before testing this.

**Pull request closed without merging**
