### PR TITLE
Adjust for change in LineInfo implementation on 0.5

### PR DESCRIPTION
**Pull request by timholy**
Gets the Gtk backend working on 0.5.

### CODE REVIEW

**Comment by lucasb-eyer** [comment]
Beautiful timing! I just ran into this and can confirm your fix works.

**Comment by KristofferC** [comment]
Is it just me that gets figures like:

image

**Comment by timholy** [comment]
What does `C=true` add?

**Comment by KristofferC** [comment]
Wow, that whole block to the right is in `libpthread`.. wtf. Must be BLAS.. something is really weird.

image

**Pull request merged**
