### PR TITLE
Fixed SVG output on Julia v0.5

### PR DESCRIPTION
**Pull request by oschulz**

### CODE REVIEW

**Comment by oschulz** [comment]
@timholy: The Travis failure seems to be due to Gtk.jl not compiling - I guess I can ignore that?

**Comment by timholy** [comment]
Thanks for this!

Looks like Gtk just needs to be tagged.

**Comment by oschulz** [comment]
Tim, would you consider making tag, so that SVG support is available in the release version of ProfileView (for Julia v0.5 )?

**Comment by timholy** [comment]
Done, thanks for the reminder. https://github.com/JuliaLang/METADATA.jl/pull/6437

**Comment by oschulz** [comment]
Thanks!

**Pull request merged**
