### PR TITLE
Add paging by thread (and task, optionally)

### PR DESCRIPTION
**Pull request by IanButterworth**
Depends on 
- julia 1.8 
- https://github.com/timholy/FlameGraphs.jl/pull/44
- https://github.com/JuliaGraphics/Gtk.jl/pull/607

```
julia> using ProfileView

julia> function myfunc()
                  A = rand(400, 400, 400)
                  maximum(A)
              end
myfunc (generic function with 1 method)

julia> myfunc();

julia> @profview myfunc()
```

ezgif com-gif-maker (1)

### CODE REVIEW

**Comment by timholy** [comment]
5sdak4

(Not real ones, anyway. I should fix that at some point, but probably not until #169.)

**Comment by timholy** [comment]
*Now* there are tests!

**Comment by timholy** [comment]
Anything here likely to be breaking? Otherwise 1.0 is ready to go.

**Comment by IanButterworth** [comment]
I don't think so. It just needs code branches depending on julia version >= 1.8 (or detecting if profile metadata is present, perhaps).
I could try to get this done over the weekend, if that's ok?

**Comment by timholy** [comment]
If it's non-breaking, there's no urgency. If it is, I'll wait. I'm pretty happy using `master` for a while.

So, :shrug: Just let me know what you want me to do, and don't distort your schedule to rush this out. I'll be starting holiday travel around the weekend anyway.

**Comment by IanButterworth** [comment]
I think it can be done without breaking, so don't let this stop 1.0

**Comment by timholy** [comment]
OK, I'll get it out. That will shake out any remaining bugs in GtkObservables/Gtk. The landmark change was a whopping two lines: https://github.com/JuliaGraphics/Gtk.jl/pull/600. The rest has been finishing WIP and merging it. But of course wider usage often turns up other issues, and I might as well see what that shakes out.

**Comment by IanButterworth** [comment]
(just a rebase at this stage)

**Comment by IanButterworth** [comment]
@timholy what do you think the save/ope buttons should do once thread paging is added? I'm thinking it should save/open all pages?

**Comment by IanButterworth** [comment]
Ok, this is passing locally for me with https://github.com/timholy/FlameGraphs.jl/pull/44 now

I originally wanted to make the load/save buttons work on all pages at once, but figuring that out was stalling this.. perhaps that could be a future PR?

**Comment by IanButterworth** [comment]
When testing this I suggest using this workaround https://github.com/JuliaLang/julia/issues/35552#issuecomment-1006685658

**Comment by IanButterworth** [comment]
I think this is ready. I'll merge and release 1.1.0

**Comment by timholy** [comment]
This looks beautiful! I will be excited to try it out.

**Comment by timholy** [comment]
Looks like we could use a test with `expand_tasks = true`?

**Pull request merged**
