### PR TITLE
Get package working on 0.7/1.0

### PR DESCRIPTION
**Pull request by timholy**
This requires https://github.com/JuliaGizmos/GtkReactive.jl/pull/76 but is, I think, otherwise ready. CC @GunnarFarneback.

### CODE REVIEW

**Comment by GunnarFarneback** [comment]
The conditional loading looks cleaner than it did before, very nice. Tests pass for me locally both without and with GtkReactive#76. Actually running ProfileView without produces just the bars, but no annotations. With I do get annotations, of sorts, but the experience can at best be described as weird. I'll check if it's the same on another computer tomorrow.

It looks like `.travis.yml` needs some `using Pkg` for 1.0.

**Comment by timholy** [comment]
I've got the Travis script update already done locally, I was just waiting for the tag to be merged to METADATA.

But it's a little concerning that you're not seeing annotations. I do see them, and in fact the image in the [new README](https://github.com/timholy/ProfileView.jl/tree/teh/julia0.7) was collected on the new version. Have you updated to the latest GtkReactive and then added GtkReactive#76? The reason I ask is because I suspect that https://github.com/JuliaGizmos/GtkReactive.jl/pull/73 was an insanely-important commit (and the only part that mattered was to delete a single line, `yield()`, from `draw`). That took me more than one whole day to track down, and since I added it myself (https://github.com/JuliaGizmos/GtkReactive.jl/pull/2) it was definitely a "kick-me" moment. I think some change in Julia's task-handling exposed the problem, but it was latent for a long time.

**Comment by GunnarFarneback** [comment]
I believe I should have the right code after doing
```
pkg> add GtkReactive#master
pkg> add ProfileView#teh/julia0.7
```
With released GtkReactive (i.e. without PR 76) I had no annotations at all. With master I get the annotation shown as I move the mouse over it, but with a lot of pixels tailing around. After moving the mouse around for a bit it can look like this:
profileview
But as I said I'd like to check with some more computer. This one isn't entirely at its best, so it could be a local problem.

**Comment by timholy** [comment]
Hmm, I have seen that. But I'm not getting it currently since that fix.

I am not sure (I'm still getting used to the new Pkg), but I think there's a chance that `add GtkReactive#master` doesn't give you the latest *if* you already have a `master` branch that you checked out earlier. Not sure though. If you use `dev` you can inspect the git log and see if it matches the one on GitHub. (If not, do a `git pull` to update.)

My guess, though, is that you are working with the latest and that we have a problem somewhere.

**Comment by GunnarFarneback** [comment]
Yes, it's the same with `dev` and a freshly pulled master.

**Comment by timholy** [comment]
That's not good. Perhaps insert some `@async @show` statements in [this block](https://github.com/timholy/ProfileView.jl/blob/dfb21327fffb4db3446aef2c6df10f46ad274024/src/ProfileViewGtk.jl#L89-L115) and see if you can figure out what's going wrong? My guess is there's some kind of mismatch between the coordinates of the erase and the coordinates of the draw, so variables like `lasttextbb`, `r`, `xu`, and `yu` seem particularly important. If you're putting it in an `@async` (which you need to, since you can't `yield` from a callback), you might want to have all them end up in the *same* `@async` otherwise timing might be confusing.

**Comment by GunnarFarneback** [comment]
Looked a bit into that but will have to wait until tomorrow to try to understand it. However, looking at what's going on on the screen I can't help getting the impression that it's erasing a flipped box, leaving the text both left and right of the center but erasing above and below in the center.

**Comment by GunnarFarneback** [comment]
Problem is fixed for me with https://github.com/JuliaGraphics/Cairo.jl/pull/254.

**Comment by timholy** [comment]
We can merge and tag this any time now. But if @lobingera agrees that we can tag a new Cairo release, I'd kind of like to make it dependent on the fixed Cairo. So I'll hold off for a little while anyway.

**Comment by GunnarFarneback** [comment]
Maybe bump Cairo lower bound to 0.5.6?

**Comment by timholy** [comment]
Thanks for all your help, @GunnarFarneback, it's been a pleasure!

**Pull request merged**
